export const PAPER_FORMATS = {
  a4: { label: "A4", width: 800, height: 1131, mmW: 210, mmH: 297 },
  a5: { label: "A5", width: 566, height: 800, mmW: 148, mmH: 210 },
  letter: { label: "US Letter", width: 800, height: 1033, mmW: 216, mmH: 279 },
  legal: { label: "US Legal", width: 800, height: 1319, mmW: 216, mmH: 356 },
  a3: { label: "A3", width: 1131, height: 1600, mmW: 297, mmH: 420 },
};

export const LAYOUT_MODES = {
  ruled: { label: "Ruled", icon: "≡", description: "Classic horizontal lines" },
  graph: { label: "Graph", icon: "⊞", description: "Square grid matrix" },
  dot: { label: "Dot Grid", icon: "⁘", description: "Bullet journal dots" },
  cornell: { label: "Cornell", icon: "▤", description: "Academic note system" },
  music: { label: "Music", icon: "♫", description: "Five-line staff" },
  blank: { label: "Blank", icon: "○", description: "Pure canvas" },
};

export const LINE_STYLES = {
  solid: { label: "Solid", dash: [] },
  dashed: { label: "Dashed", dash: [12, 8] },
  dotted: { label: "Dotted", dash: [2, 6] },
};

export const EXPORT_QUALITIES = {
  standard: { label: "Standard", dpi: 150, badge: "Screen" },
  print: { label: "Print Ready", dpi: 300, badge: "Pro" },
  archival: { label: "Archival", dpi: 600, badge: "Enterprise" },
};

export const PRESETS = {
  executive: {
    name: "Executive Suite",
    tag: "Signature",
    spacing: 80,
    thickness: 3,
    ruleColor: "#B8B8B8",
    paperColor: "#FFFEF9",
    side: 340,
    sideWidth: 4,
    sideColor: "#C9A962",
    layoutMode: "ruled",
    lineStyle: "solid",
  },
  manhattan: {
    name: "Manhattan Noir",
    tag: "Limited",
    spacing: 70,
    thickness: 2,
    ruleColor: "#3A3A3C",
    paperColor: "#FAFAFA",
    side: 300,
    sideWidth: 5,
    sideColor: "#1C1C1F",
    layoutMode: "ruled",
    lineStyle: "solid",
  },
  oxford: {
    name: "Oxford Classic",
    tag: "Heritage",
    spacing: 85,
    thickness: 4,
    ruleColor: "#94A3B8",
    paperColor: "#FFFFFF",
    side: 320,
    sideWidth: 6,
    sideColor: "#DC2626",
    layoutMode: "ruled",
    lineStyle: "solid",
  },
  atelier: {
    name: "Atelier Pastel",
    tag: "Studio",
    spacing: 65,
    thickness: 3,
    ruleColor: "#FBCFE8",
    paperColor: "#FFFBF5",
    side: 280,
    sideWidth: 5,
    sideColor: "#C084FC",
    layoutMode: "ruled",
    lineStyle: "solid",
  },
  precision: {
    name: "Precision Grid",
    tag: "Engineering",
    spacing: 60,
    thickness: 2,
    ruleColor: "#CBD5E1",
    paperColor: "#FFFFFF",
    side: 300,
    sideWidth: 4,
    sideColor: "#2563EB",
    layoutMode: "graph",
    lineStyle: "solid",
  },
  bullet: {
    name: "Bullet Journal",
    tag: "Productivity",
    spacing: 50,
    thickness: 2,
    ruleColor: "#D1D5DB",
    paperColor: "#FFFEF9",
    side: 240,
    sideWidth: 3,
    sideColor: "#9CA3AF",
    layoutMode: "dot",
    lineStyle: "solid",
  },
  scholar: {
    name: "Scholar Cornell",
    tag: "Academic",
    spacing: 75,
    thickness: 3,
    ruleColor: "#A1A1AA",
    paperColor: "#FFFFFF",
    side: 280,
    sideWidth: 4,
    sideColor: "#71717A",
    layoutMode: "cornell",
    lineStyle: "solid",
  },
  symphony: {
    name: "Symphony",
    tag: "Creative",
    spacing: 90,
    thickness: 2,
    ruleColor: "#1C1C1F",
    paperColor: "#FFFEF9",
    side: 200,
    sideWidth: 3,
    sideColor: "#C9A962",
    layoutMode: "music",
    lineStyle: "solid",
  },
};

export const DEFAULT_SETTINGS = {
  spacing: 80,
  thickness: 3,
  ruleColor: "#B8B8B8",
  paperColor: "#FFFEF9",
  side: 340,
  sideWidth: 4,
  sideColor: "#C9A962",
  format: "a4",
  orientation: "portrait",
  layoutMode: "ruled",
  lineStyle: "solid",
  headerText: "",
  footerText: "",
  watermarkText: "",
  watermarkOpacity: 0.06,
  pageCount: 1,
  exportQuality: "print",
  showMeasurements: true,
};

export const STORAGE_KEY = "paperstudio-pro-v1";

export const KEYBOARD_SHORTCUTS = [
  { keys: ["⌘", "K"], action: "Command palette" },
  { keys: ["⌘", "Z"], action: "Undo" },
  { keys: ["⌘", "⇧", "Z"], action: "Redo" },
  { keys: ["⌘", "S"], action: "Export PDF" },
  { keys: ["⌘", "E"], action: "Export PNG" },
  { keys: ["⌘", "C"], action: "Copy config" },
  { keys: ["⌘", "0"], action: "Reset zoom" },
  { keys: ["⌘", "+"], action: "Zoom in" },
  { keys: ["⌘", "-"], action: "Zoom out" },
  { keys: ["F"], action: "Fullscreen preview" },
  { keys: ["?"], action: "Shortcuts" },
];